### ISSUE TITLE
Texts on screen sometimes stay forever

### ISSUE THREAD

**Issue by LaFesta1749** [Vretu-Dev/UsefulHints#3]
Using version 1.8.2

![image](https://github.com/user-attachments/assets/cee6b727-04f3-4ae8-bcbc-ada889e99c07)

https://medal.tv/games/scp-secret-laboratory/clips/jjj5in13cjUTmHp-p?invite=cr-MSw0a0gsMjYzMjA5ODI5LA

**Comment by Vretu-Dev** [comment]
Are you using Meow Hint Service?

> Using version 1.8.2
> 
> ![image](https://private-user-images.githubusercontent.com/1494298/397079293-cee6b727-04f3-4ae8-bcbc-ada889e99c07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTE0ODcsIm5iZiI6MTczNDU1MTE4NywicGF0aCI6Ii8xNDk0Mjk4LzM5NzA3OTI5My1jZWU2YjcyNy0wNGYzLTRhZTgtYmNiYy1hZGE4ODllOTljMDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMTk0NjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmUzNThkMTU3NDg2MDkxMGYxMjk4MDdhNmQ5Yjg5ZmJiNGI4YTRhODYwYThkMWQwN2E2YjNjZDUxZjZjMzMwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CZjS8XjK0_6xN4mYWVGavBB97KDxtCRtsZrXVdSYMSY)
> 
> https://medal.tv/games/scp-secret-laboratory/clips/jjj5in13cjUTmHp-p?invite=cr-MSw0a0gsMjYzMjA5ODI5LA

**Comment by LaFesta1749** [comment]
yes @Vretu-Dev

**Comment by Vretu-Dev** [comment]
> yes @Vretu-Dev

Unfortunately, this is due to. In the future I will add support for the Meow Hint service

**Comment by Vretu-Dev** [comment]
Version for HintServiceMeow Done
