### ISSUE TITLE
When the gift box for the Christmas tree is opened, the activated grenade generated by the Christmas tree will cause the round to freeze.

### ISSUE THREAD

**Issue by kldhsh123** [Vretu-Dev/UsefulHints#4]
Sorry my English is not very good, the description may be a little unclear. When the gift box for the Christmas tree is opened, the activated grenade generated by the Christmas tree will cause the round to freeze. I cannot provide error information because no errors appeared in the console. However, this issue was resolved after I removed the UsefulHints plugin.

**Comment by Vretu-Dev** [comment]
https://github.com/Vretu-Dev/UsefulHints/releases/tag/1.9.1

**Comment by Vretu-Dev** [comment]
Try this one

**Comment by Vretu-Dev** [comment]
> Sorry my English is not very good, the description may be a little unclear. When the gift box for the Christmas tree is opened, the activated grenade generated by the Christmas tree will cause the round to freeze. I cannot provide error information because no errors appeared in the console. However, this issue was resolved after I removed the UsefulHints plugin.

Try this one
https://github.com/Vretu-Dev/UsefulHints/releases/tag/1.9.1

**Comment by kldhsh123** [comment]
Thank you
